# Introduction to Tensors and TensorFlow

Before we start using TensorFlow for neural networks and deep learning, we learn that TensorFlow is a powerful library for
mathematical operations and optimization "under the hood".
Using a few simple examples we understand more about the variables used in TensorFlow.

## A Brief Reminder of Scalars, Vectors and Tensors

Numbers are at the core of mathematics. In some scenarios, a simple number is sufficient, e.g. "How many pieces of cake are there?" - and you might answer "6 (pieces of cake)".

However, in many situations a simple number is not sufficient, e.g. "How far is it to your home". Just answering "3" is not sufficient, we now need a _unit_, e.g. km: "My house is 3 km from here. These numbers are called denominate numbers or **scalars**. Other examples are temperature, energy, etc.

In other situations, more information is required than denominate numbers, e.g. answering the question "How do I get to your house?" In addition to a number, a direction is needed: "Walk 3 km due north". These numbers are **vectors**, other examples are velocity, momentum, ...
Vectors are often represented by their components: $\vec{v} = a * \vec{i} + b * \vec{j} + c *\vec{k}$, where $\vec{i}, \vec{j}, \vec{k}$ are the unit vectors (for example, in x,y,z direction in Eucledian space) and a,b,c are scalars denoting how far one has to go in each direction.

### Vectors
Vectors can be combined into new objects:
* Sum: $\vec{W} = \vec{U} + \vec{V}$
The sum (or difference) of two vectors results in a new vector
* Inner Product: $\vec{U} + \vec{V} = \eta$
The inner prduct results in a scalar, the inner product of a vector with itself is the square of its magnitude (length)
* Cross Product: $\vec{S} = \vec{U} \times \vec{V}$
Two vectors in 3-dimensional space can be combined into a new vector, where the resulting vector $\vec{S}$ is perpendicular to the plane spanned by $\vec{U}$ and $\vec{V}$ and its direction is given by the right-hand-rule.
* Multiplied by scalar: A vector can be multiplied by a scalar to change its magnitude.

### Tensors
If we start from a unit vector and want to change its properties, we have few options so far:
* multiply with a scalar to change its magnitude
* cross product with another (unit) vector to change its direction.
However, this limits us to right angles - if we want to change both magnitude and direction of a vector, we need something else: **tensors** 

__Terminology__

* Scalar: Tensor of rank 0 (magnitude only - 1 component)
* Vector: Tensor of rank 1 (magnitude and 1 direction - 3 components)
* Dyad:   Tensor of rank 2 (magnigude and 2 directions - $3^2 = 9$ components)
* Triad:  Tensor of rank 3 (magnitude and 3 directions - $3^3 = 27$ components)

__Dyad Product__

A dyad can be constructed from two vectors by taking the product of the components term-by-term of each individual components and then adding them element-wise. The dyad product of two vectors $\vec{U}$ and $\vec{V}$ is then simply $\underline{UV} = \vec{U} \vec{V}$, which is neither a dot nor a cross product.
If $\vec{U}= u_1 \vec{i} + u_2 \vec{j} + u_3 \vec{k}$ and $\vec{V}= v_1 \vec{i} + v_2 \vec{j} + v_3 \vec{k}$, the dyad product is given by $\underline{UV} = u_1v_1 \underline{ii} + u_1v_2 \underline{ij} + u_1v_3\underline{ik} + \cdots$. Here, $\vec{i}$, $\vec{j}$, $\vec{k}$ are unit vectors and $\underline{ii}$, $\underline{ij}$, etc are unit dyads.
Setting $\mu_{11} = u_1v_1$, $\mu_{12} = u_1v_2$, the dyad product can be written as $\underline{UV} =  \mu_{11} \underline{ii} +\mu_{12} \underline{ij} + \mu_{13}\underline{ik} + \cdots$. The scalar components $\mu_{ij}$ can be expressed as a matrix:
$$
\begin{array}{ccc}
\mu_{11} & \mu_{12} & \mu_{12} \\
\mu_{21} & \mu_{22} & \mu_{22} \\
\mu_{31} & \mu_{32} & \mu_{32} 
\end{array}
$$
Note that the dyad product is generally not commutative, i.e., $\underline{UV}\ne\underline{VU}$.

__Calculating with Tensors__

Calculating with dyads is similar to matrix operations, the rules are generally not commutative, i.e., the order matters.

Multiplying with a scalar is defined as $a(\underline{UV}) = (\underline{UV})a$, i.e. pre- and post-multiplication give the same result

The inner product of a dyad $\underline{UV}$ with another vector $\vec{S}$ is defined as $\vec{S}\cdot (\underline{UV})$ when we pre-multiply and $(\underline{UV}) \cdot \vec{S}$ when we post-multiply.
The order makes a difference: When we pre-multiply: $\vec{S} \cdot \underline{UV} = (\vec{S} \cdot \vec{U})\vec{V} = \sigma \vec{V}$, i.e. the result is a vector with magnitude $\sigma = \vec{S} \cdot \vec(U)$ and direction of $\vec{V}$. For post-multiplication, $\underline{UV}\cdot\vec{S} = \vec{U}(\vec{V}\cdot \vec{S}) = \lambda \vec{U}$, i.e. a vector with magnitude $\lambda = \vec{V}\cdot\vec{S}$ in direction of $\vec{U}$.

In [ ]:
# import required libraries
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.1.0


## Example: Scalars

Let's start with some simple examples. 
We define two scalar variables as constants, multiply them and print the result.

In Python we would simply write:


In [ ]:
a = 5.0
b = 6.0
c = a*b
print(c)

30.0


Now we use the TensorFlow equivalents:

In [ ]:
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
print(c)

tf.Tensor(30.0, shape=(), dtype=float32)


We notice that instead the expected printout of ```30``` we obtain a ```tf.Tensor``` object.
Its value is indeed ```30``` and the (inferred) type is a 32-bit floating point number. We also see the parameter ```shape``` which is essentially
indicating the dimensionality of the tensor. As we use a scalar, this is empty.

In some cases we're just interested in the value, not in the tensor.
Since numpy is more or less the de-facto standard for numerical handling in python, TensorFlow provides the `numpy` method to return the result in this format.

In [ ]:
print(c.numpy())

30.0


## Example: Matrix Operations


As mentioned above, TensorFlow works well together with the de-facto standard for numerical manipulation in python: ```numpy```.
For example, we can define a matrix in numpy and manipulate it using TensorFlow and the ```numpy``` object gets converted to a TensorFlow Tensor automatically.

In this example, we first define a matrix in numpy and then add 1 to each element using TensorFlow

In [ ]:
A = [[1, 2],
     [3, 4]]
print (A)

[[1, 2], [3, 4]]


As a simple example, we add ```1``` to this - TensorFlow implicitly constructs a matrix of appropriate size where all values are filled with ```1```.

In [ ]:
B = tf.add(A,1)
print(B)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


Now we notice that the ```shape``` parameter is used. Since this is a 2x2 matrix, the shape is specified as ```(2,2)``` accordingly.
Note that we used integer numbers in this example and the type of the tensor constructed by Tensorflow is ```int32```.

As the next example, lets add or multiply two matrices:


In [ ]:
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]



In [ ]:
print(tf.add(A,B))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [ ]:
print(tf.matmul(A,B))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## Example: Variables

So far, we've encountered static components such as a constant or a matrix.
In more realistic cases we need to manipulate variables, i.e., unknowns $x$ which can hold arbitrary values.
More on variables in TensorFlow [here](https://www.tensorflow.org/guide/variable)

TensorFlow provides ```tf.Variable``` to define variables, alternatively, 
```my_var = tf.Variable(<inital value>,name="my_var")```

As an example, we initialize a real-valued variable $x$ called "x" with zeros.
We use the helper function ```tf.zeros``` described [here](https://www.tensorflow.org/api_docs/python/tf/zeros)
to initialize the variable. In our simple example, we use a one-dimensional variable. In more complex
situations, we can specify a shape accordingly, as well as specifying the type explicitly.

In [ ]:
x = tf.Variable(tf.zeros([1]), name='x')
print(x)

<tf.Variable 'x:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>


In [ ]:
y = tf.Variable(tf.zeros([2,2], tf.float32), name='y')
print(y)

<tf.Variable 'y:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>
